# Generated by Django 5.2.12 on 2026-04-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_booking_alter_review_comment_and_more'),
    ]

    operations = [
    ]
