# Generated by Django 5.2.12 on 2026-04-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_initial'),
    ]

    operations = [
    ]
